packages:
   - apps/*
   - packages/*
   - tooling/*

catalog:
   "@better-auth/cli": ^1.4.6
   "@eslint/js": ^9.38.0
   "@lucide/svelte": ^0.563.1
   "@sveltejs/kit": ^2.50
   "@sveltejs/vite-plugin-svelte": 5.1.0
   tw-animate-css: ^1.4.0
   "@tailwindcss/postcss": ^4.1.16
   "@tailwindcss/vite": ^4.1.16
   "@types/node": 22.18.12
   "@trpc/client": "^11.8.1"
   "@trpc/server": "^11.8.1"
   better-auth: ^1.4.6
   eslint: ^9.39.1
   prettier: ^3.7.4
   shadcn-svelte: ^2.0.0
   svelte: ^5.48
   svelte-check: ^4.3
   tailwindcss: ^4.1.17
   typescript: ^5.9.3
   vite: ^7.3
   zod: ^4.1.13

ignoredBuiltDependencies:
   - sharp

linkWorkspacePackages: true

onlyBuiltDependencies:
   - "@tailwindcss/oxide"
   - esbuild
   - msw

overrides:
   "@types/minimatch": 5.1.2
   lightningcss: 1.30.1
   vite: 7.3.1

publicHoistPattern:
   - "@ianvs/prettier-plugin-sort-imports"
   - prettier-plugin-tailwindcss
   - prettier-plugin-svelte
